spring:
  server:
    port: 8080
    host: localhost
  config:
    activate-mongodb: ${ACTIVATE_MONGODB}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      user: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      auth-mechanism: ${MONGODB_AUTH_MECHANISM}
    hubspot:
      token-reactive-api: ${TOKEN_HUBSPOT}
      endpoints:
        url: https://api.hubspot.com/crm/v3/objects/contacts